sonar.host.url=http://localhost:9000
sonar.projectKey=kata-rose
sonar.projectName=Kata Gilded Rose in Java (Almunia)
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8
